<!DOCTYPE html>
<html>
    <head>
      <meta charset="utf-8">
      <title> Listado Empleado </title>
      <meta name="description" content="">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
    <body>
      <div id="main" role="main">
      	<div id="content" class="container">
          <nav class="navbar navbar-default" role="navigation">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse"
                      data-target=".navbar-ex1-collapse">
                <span class="sr-only">Desplegar navegación</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="../public">Back End</a>
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="../public/empleado">Listado Empleados</a></li>
				<li class="actives"><a href="../public/salario">Filtro Salario</a></li>
              </ul>
            </div>
          </nav>

          <h1>Empleados</h1>
          <legend></legend>

              <div class="form-group">
                <form method="GET">
											<label class="col-md-1 control-label">Buscar</label>
											<div class="col-md-6">
                        <input type="text" class="form-control" name="correo" placeholder="email">
											</div>
                      <div class="col-md-3">
                        <button type="submit" class="btn btn-success">Buscar</button>
											</div>
                </form>
							</div>
              <br><br><br>
              <div class="form-group">
                  <table class="table table-bordered">
                    <thead>
                      <tr>
                          <th>Nombre</th>
                          <th>Email</th>
                          <th>Puesto</th>
                          <th>Salario</th>
                          <th>Opciones</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php foreach ($empleado as $datos): ?>
                          <tr>
                              <td><?php echo $datos['name']; ?></td>
                              <td><?php echo $datos['email']; ?></td>
                              <td><?php echo $datos['position']; ?></td>
                              <td><?php echo $datos['salary']; ?></td>
                              <td>
                                  <button data-toggle="modal" data-target="#id_<?php echo $datos['id'];?>" class="btn btn-info">Ver Datos</button>
                              </td>
                          </tr>
                      <?php endforeach; ?>
                    </tbody>
                  </table>
              </div>
        </div>
      </div>

        <?php foreach ($empleado as $datos):?>
          <div class="modal fade" id="id_<?php echo $datos['id'];?>">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title">Datos Empleado: <strong><?php echo $datos['id'];?></strong></h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <fieldset>
                  				<div class="form-group">
                  					<div class="row">
                  						<div class="col-md-6">
                  							<label class="col-md-3 control-label"><strong>Nombre</strong></label>
                  							<span class="col-md-9 control-label"><?php echo $datos['name']; ?></span>
                  						</div>
                  						<div class="col-md-6">
                  							<label class="col-md-3 control-label"><strong>Email</strong> </label>
                  							<span class="col-md-8 control-label"><?php echo $datos['email']; ?></span>
                  						</div>
                  					</div>

                  					<div class="row">
                              <div class="col-md-6">
                  							<label class="col-md-3 control-label"><strong>Telefono</strong></label>
                  							<span class="col-md-9 control-label"><?php echo $datos['phone']; ?></span>
                  						</div>
                              <div class="col-md-6">
                  							<label class="col-md-3 control-label"><strong>Sueldo</strong></label>
                  							<span class="col-md-9 control-label"><?php echo $datos['salary']; ?></span>
                  						</div>
                  					</div>

                  					<div class="row">
                              <div class="col-md-6">
                  							<label class="col-md-3 control-label"><strong>Puesto</strong></label>
                  							<span class="col-md-9 control-label"><?php echo $datos['position']; ?></span>
                  						</div>
                  					</div>

                            <div class="row">
                              <div class="col-md-12">
                  							<label class="col-md-2 control-label"><strong>Direccion</strong></label>
                  							<span class="col-md-10 control-label"><?php echo $datos['address']; ?></span>
                  						</div>
                            </div>

                            <div class="row">
                              <div class="col-md-12">
                  							<label class="col-md-2 control-label"><strong>Habilidades</strong></label>
                  							<span class="col-md-10 control-label">
                                  <?php foreach($datos['skills'] as $skill):?>
                                    <?php echo $skill['skill'] ?>
                                  <?php  endforeach;?>
                                </span>
                  						</div>
                            </div>

                  				</div>
                  				</fieldset>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        <?php endforeach; ?>
    </body>
</html>
