<!DOCTYPE html>
<html>
    <head>
      <meta charset="utf-8">
      <title> Back End Test </title>
      <meta name="description" content="">
		  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
		  <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
	</head>
    <body>
		<div id="wrapper">
			<h1>Back End - Aplication Test</h1>
			<legend></legend>
			<div class="container-fluid">
				<div class="row">
				  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">  </div>
				  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12"><a href="../public/empleado">Lista Empleados</a> </div>
				  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12"><a href="../public/salario"> Filtro Salario</a> </div>
				  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12"> </div>
				 </div>
			</div>
		</div>
    </body>
</html>
